apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.env.secrets.SECRET_KEY | b64enc }}
  FIRST_SUPERUSER: {{ .Values.env.secrets.FIRST_SUPERUSER | b64enc }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.env.secrets.FIRST_SUPERUSER_PASSWORD | b64enc }}
  USERS_OPEN_REGISTRATION: {{ .Values.env.secrets.USERS_OPEN_REGISTRATION | b64enc }}
  POSTGRES_SERVER: {{ .Values.env.secrets.POSTGRES_SERVER | b64enc }}
  POSTGRES_DB: {{ .Values.env.secrets.POSTGRES_DB | b64enc }}
  POSTGRES_USER: {{ .Values.env.secrets.POSTGRES_USER | b64enc }}
  POSTGRES_PORT: {{ .Values.env.secrets.POSTGRES_PORT | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.env.secrets.POSTGRES_PASSWORD | b64enc }}
  POSTGRES_SSL_MODE: {{ .Values.env.secrets.POSTGRES_SSL_MODE | b64enc }}
  REDIS_HOST: {{ .Values.env.secrets.REDIS_HOST | b64enc }}
  REDIS_PORT: {{ .Values.env.secrets.REDIS_PORT | b64enc }}
  REDIS_DB: {{ .Values.env.secrets.REDIS_DB | b64enc }}
  DISCOURSE_CONNECT_ENABLED: {{ .Values.env.secrets.DISCOURSE_CONNECT_ENABLED | b64enc }}
  DISCOURSE_CONNECT_SECRET: {{ .Values.env.secrets.DISCOURSE_CONNECT_SECRET | b64enc }}
  DISCOURSE_CONNECT_URL: {{ .Values.env.secrets.DISCOURSE_CONNECT_URL | b64enc }}
  MAPBOX_ACCESS_TOKEN: {{ .Values.env.secrets.MAPBOX_ACCESS_TOKEN | b64enc }}
  MINIO_ROOT_USER: {{ .Values.env.secrets.MINIO_ROOT_USER | b64enc }}
  MINIO_ROOT_PASSWORD: {{ .Values.env.secrets.MINIO_ROOT_PASSWORD | b64enc }}
  MINIO_BUCKET_NAME: {{ .Values.env.secrets.MINIO_BUCKET_NAME | b64enc }}
  MINIO_REGION: {{ .Values.env.secrets.MINIO_REGION | b64enc }}
  MINIO_ACCESS_KEY: {{ .Values.env.secrets.MINIO_ACCESS_KEY | b64enc }}
  MINIO_SECRET_KEY: {{ .Values.env.secrets.MINIO_SECRET_KEY | b64enc }}
  MINIO_USE_SSL: {{ .Values.env.secrets.MINIO_USE_SSL | b64enc }}
  MINIO_SITE_NAME: {{ .Values.env.secrets.MINIO_SITE_NAME | b64enc }}
  MINIO_SITE_REGION: {{ .Values.env.secrets.MINIO_SITE_REGION | b64enc }}
  SMTP_HOST: {{ .Values.env.secrets.SMTP_HOST | b64enc }}
  SMTP_PORT: {{ .Values.env.secrets.SMTP_PORT | b64enc }}
  SMTP_TLS: {{ .Values.env.secrets.SMTP_TLS | b64enc }}
  SMTP_USER: {{ .Values.env.secrets.SMTP_USER | b64enc }}
  SMTP_PASSWORD: {{ .Values.env.secrets.SMTP_PASSWORD | b64enc }}
  EMAILS_FROM_EMAIL: {{ .Values.env.secrets.EMAILS_FROM_EMAIL | b64enc }}
  SMTP_SSL: {{ .Values.env.secrets.SMTP_SSL | b64enc }}
  OPENAI_API_KEY: {{ .Values.env.secrets.OPENAI_API_KEY | b64enc }}
  GOOGLE_API_KEY: {{ .Values.env.secrets.GOOGLE_API_KEY | b64enc }}
  TAVILY_API_KEY: {{ .Values.env.secrets.TAVILY_API_KEY | b64enc }}
  WIPE_DB: {{ .Values.env.secrets.WIPE_DB | b64enc }}