apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
      containers:
        - name: celery-worker
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.configmaps.stack.name }}
            - secretRef:
                name: {{ .Release.Name }}-secrets
          command:
            - celery
          args:
            - -A
            - app.core.celery_app.celery
            - worker
            - --loglevel=info
            - -P
            - prefork
            - --concurrency=4
          livenessProbe:
            exec:
              command:
                - celery
                - -A
                - app.core.celery_app.celery
                - inspect
                - ping
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 6
          startupProbe:
            exec:
              command:
                - celery
                - -A
                - app.core.celery_app.celery
                - inspect
                - ping
            # Allow up to ~5 minutes for Redis to become reachable and worker to come up
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 20
          readinessProbe:
            exec:
              command:
                - celery
                - -A
                - app.core.celery_app.celery
                - inspect
                - ping
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 20
            failureThreshold: 6
          resources:
            limits:
              cpu: {{ .Values.resources.celery.limits.cpu }}
              memory: {{ .Values.resources.celery.limits.memory }}
            requests:
              cpu: {{ .Values.resources.celery.requests.cpu }}
              memory: {{ .Values.resources.celery.requests.memory }}
