apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - "10.43.0.10" # CoreDNS Service IP
        options:
          - name: ndots
            value: "1"
      containers:
        - name: celery-worker
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.configmaps.stack.name }}
            - secretRef:
                name: {{ .Release.Name }}-secrets
          command:
            - /app/start.sh
          args:
            - celery
            - -A
            - app.core.celery_app.celery
            - worker
            - --loglevel=info
            - -P
            - prefork
            - --concurrency=4
          readinessProbe:
            exec:
              command:
                - celery
                - -A
                - app.core.celery_app.celery
                - inspect
                - ping
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
