"""initial migration

Revision ID: 51742cad3d53
Revises: 305c0b8dc78d
Create Date: 2025-04-24 13:22:27.113556

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '51742cad3d53'
down_revision = '305c0b8dc78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shareable_links',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('permission_level', sa.Enum('READ_ONLY', 'EDIT', 'FULL_ACCESS', name='permissionlevel'), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('requires_login', sa.Boolean(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('DATA_SOURCE', 'SCHEMA', 'WORKSPACE', 'CLASSIFICATION_JOB', 'DATASET', name='resourcetype'), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shareable_links_token'), 'shareable_links', ['token'], unique=True)
    op.create_index(op.f('ix_shareable_links_user_id'), 'shareable_links', ['user_id'], unique=False)
    op.create_table('dataset',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('datarecord_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('source_job_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('source_scheme_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('datarecord', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('datarecord', 'datasource_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_datarecord_content_hash'), 'datarecord', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datarecord_content_hash'), table_name='datarecord')
    op.alter_column('datarecord', 'datasource_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('datarecord', 'content_hash')
    op.drop_table('dataset')
    op.drop_index(op.f('ix_shareable_links_user_id'), table_name='shareable_links')
    op.drop_index(op.f('ix_shareable_links_token'), table_name='shareable_links')
    op.drop_table('shareable_links')
    # ### end Alembic commands ###
