"""initial migration

Revision ID: 870b15c7bdef
Revises: 9ba32145ed15
Create Date: 2025-04-25 22:28:14.865912

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '870b15c7bdef'
down_revision = '9ba32145ed15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
