"""initial migration

Revision ID: f78ccdaf565c
Revises: eec107359b43
Create Date: 2025-04-28 19:17:48.806055

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f78ccdaf565c'
down_revision = 'eec107359b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
