"""Make run_id optional in classification_result

Revision ID: 8adf8beb74e4
Revises: f14ba1ae33ed
Create Date: 2025-04-07 22:51:02.956458

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8adf8beb74e4'
down_revision = 'f14ba1ae33ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
