"""add is_active to annotation_schemas

Revision ID: 051b7a678c21
Revises: 42330dd45cdb
Create Date: 2025-06-13 10:16:21.946989

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '051b7a678c21'
down_revision = '42330dd45cdb'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotationschema', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.create_index(op.f('ix_annotationschema_is_active'), 'annotationschema', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotationschema_is_active'), table_name='annotationschema')
    op.drop_column('annotationschema', 'is_active')
    # ### end Alembic commands ###
