"""Sources

Revision ID: 135eb21fba40
Revises: b44519e6e829
Create Date: 2025-09-28 16:58:44.926315

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '135eb21fba40'
down_revision = 'b44519e6e829'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'source', ['source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'source_id')
    # ### end Alembic commands ###
