"""treenode indicators

Revision ID: 343caeaf5873
Revises: 3ebae5284059
Create Date: 2025-12-08 21:55:09.254312

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '343caeaf5873'
down_revision = '3ebae5284059'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    # First, set a default value for existing NULL rows
    op.execute("UPDATE annotationrun SET trigger_type = 'manual' WHERE trigger_type IS NULL")
    
    # Then make the column NOT NULL
    op.alter_column('annotationrun', 'trigger_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('annotationrun', 'trigger_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
