"""Initial migration for new datastructure

Revision ID: 35535638c822
Revises: 8b8a0ae85188
Create Date: 2025-04-22 08:50:39.349551

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '35535638c822'
down_revision = '8b8a0ae85188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
