"""source status enums

Revision ID: 3ebae5284059
Revises: 8e8816728151
Create Date: 2025-12-08 20:01:16.789414

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '3ebae5284059'
down_revision = '8e8816728151'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    # Removed nullable=False constraint on trigger_type to avoid NotNullViolation error
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
