"""Add enable_related_assets flag to infospace

Revision ID: 4464015613e4
Revises: cc6cd17c5c9b
Create Date: 2026-02-10 13:26:00.989117

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '4464015613e4'
down_revision = 'cc6cd17c5c9b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "infospace",
        sa.Column(
            "enable_related_assets",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('infospace', 'enable_related_assets')
    # ### end Alembic commands ###
