"""add graph_config to annotationrun

Revision ID: 4dd003f7ac2a
Revises: c3caa8a11610
Create Date: 2026-01-11 16:56:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dd003f7ac2a'
down_revision = 'c3caa8a11610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotationrun', sa.Column('graph_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotationrun', 'graph_config')
    # ### end Alembic commands ###
