"""Recurring tasks

Revision ID: 56447d6e5cc7
Revises: 94709875c22a
Create Date: 2025-04-23 00:10:38.396657

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '56447d6e5cc7'
down_revision = '94709875c22a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurringtask',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('INGEST', 'CLASSIFY', name='recurringtasktype'), nullable=True),
    sa.Column('schedule', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ERROR', name='recurringtaskstatus'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_run_message', sa.Text(), nullable=True),
    sa.Column('last_job_id', sa.Integer(), nullable=True),
    sa.Column('consecutive_failure_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['last_job_id'], ['classificationjob.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('datarecord', sa.Column('url_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_datarecord_url_hash'), 'datarecord', ['url_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datarecord_url_hash'), table_name='datarecord')
    op.drop_column('datarecord', 'url_hash')
    op.drop_table('recurringtask')
    # ### end Alembic commands ###
