"""adding chat conversation history

Revision ID: 6872204102af
Revises: 89838ff6bf75
Create Date: 2025-09-30 18:44:54.967316

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '6872204102af'
down_revision = '89838ff6bf75'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatconversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('infospace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('conversation_metadata', sa.JSON(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['infospace_id'], ['infospace.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatconversation_updated', 'chatconversation', ['updated_at'], unique=False)
    op.create_index('ix_chatconversation_user_infospace', 'chatconversation', ['user_id', 'infospace_id'], unique=False)
    op.create_index(op.f('ix_chatconversation_uuid'), 'chatconversation', ['uuid'], unique=True)
    op.create_table('chatconversationmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_executions', sa.JSON(), nullable=True),
    sa.Column('thinking_trace', sa.Text(), nullable=True),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('usage', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chatconversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatconversationmessage_conversation', 'chatconversationmessage', ['conversation_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chatconversationmessage_conversation', table_name='chatconversationmessage')
    op.drop_table('chatconversationmessage')
    op.drop_index(op.f('ix_chatconversation_uuid'), table_name='chatconversation')
    op.drop_index('ix_chatconversation_user_infospace', table_name='chatconversation')
    op.drop_index('ix_chatconversation_updated', table_name='chatconversation')
    op.drop_table('chatconversation')
    # ### end Alembic commands ###
