"""adding 'views_config' to annotation run

Revision ID: 6eac30402cbb
Revises: 3b114def669a
Create Date: 2025-07-03 17:26:36.201018

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6eac30402cbb'
down_revision = '3b114def669a'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotationrun', sa.Column('views_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotationrun', 'views_config')
    # ### end Alembic commands ###
