"""Add nested bundle support

Revision ID: 89838ff6bf75
Revises: bea15ef4b463
Create Date: 2025-09-29 23:13:33.334578

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '89838ff6bf75'
down_revision = 'bea15ef4b463'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bundle', sa.Column('parent_bundle_id', sa.Integer(), nullable=True))
    op.add_column('bundle', sa.Column('child_bundle_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_bundle_parent_bundle_id'), 'bundle', ['parent_bundle_id'], unique=False)
    op.create_foreign_key(None, 'bundle', 'bundle', ['parent_bundle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bundle', type_='foreignkey')
    op.drop_index(op.f('ix_bundle_parent_bundle_id'), table_name='bundle')
    op.drop_column('bundle', 'child_bundle_count')
    op.drop_column('bundle', 'parent_bundle_id')
    # ### end Alembic commands ###
