"""pipeline preparations

Revision ID: 8e8816728151
Revises: 1b41703f4549
Create Date: 2025-12-08 19:15:11.912762

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '8e8816728151'
down_revision = '1b41703f4549'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcepollhistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_ingested', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_pipeline', sa.Boolean(), nullable=False),
    sa.Column('triggered_run_id', sa.Integer(), nullable=True),
    sa.Column('cursor_before', sa.JSON(), nullable=True),
    sa.Column('cursor_after', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.ForeignKeyConstraint(['triggered_run_id'], ['annotationrun.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('annotationrun', sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('annotationrun', sa.Column('trigger_context', sa.JSON(), nullable=True))
    op.add_column('annotationrun', sa.Column('pipeline_execution_id', sa.Integer(), nullable=True))
    op.add_column('annotationrun', sa.Column('triggered_by_source_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'annotationrun', 'source', ['triggered_by_source_id'], ['id'])
    op.create_foreign_key(None, 'annotationrun', 'pipelineexecution', ['pipeline_execution_id'], ['id'])
    op.add_column('intelligencepipeline', sa.Column('source_stream_ids', sa.JSON(), nullable=True))
    op.add_column('source', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('source', sa.Column('poll_interval_seconds', sa.Integer(), nullable=False))
    op.add_column('source', sa.Column('output_bundle_id', sa.Integer(), nullable=True))
    op.add_column('source', sa.Column('linked_pipeline_id', sa.Integer(), nullable=True))
    op.add_column('source', sa.Column('auto_trigger_pipeline', sa.Boolean(), nullable=False))
    op.add_column('source', sa.Column('cursor_state', sa.JSON(), nullable=True))
    op.add_column('source', sa.Column('last_poll_at', sa.DateTime(), nullable=True))
    op.add_column('source', sa.Column('next_poll_at', sa.DateTime(), nullable=True))
    op.add_column('source', sa.Column('items_last_poll', sa.Integer(), nullable=False))
    op.add_column('source', sa.Column('total_items_ingested', sa.Integer(), nullable=False))
    op.add_column('source', sa.Column('consecutive_failures', sa.Integer(), nullable=False))
    op.add_column('source', sa.Column('last_error_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'source', 'intelligencepipeline', ['linked_pipeline_id'], ['id'])
    op.create_foreign_key(None, 'source', 'bundle', ['output_bundle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.drop_constraint(None, 'source', type_='foreignkey')
    op.drop_column('source', 'last_error_at')
    op.drop_column('source', 'consecutive_failures')
    op.drop_column('source', 'total_items_ingested')
    op.drop_column('source', 'items_last_poll')
    op.drop_column('source', 'next_poll_at')
    op.drop_column('source', 'last_poll_at')
    op.drop_column('source', 'cursor_state')
    op.drop_column('source', 'auto_trigger_pipeline')
    op.drop_column('source', 'linked_pipeline_id')
    op.drop_column('source', 'output_bundle_id')
    op.drop_column('source', 'poll_interval_seconds')
    op.drop_column('source', 'is_active')
    op.drop_column('intelligencepipeline', 'source_stream_ids')
    op.drop_constraint(None, 'annotationrun', type_='foreignkey')
    op.drop_constraint(None, 'annotationrun', type_='foreignkey')
    op.drop_column('annotationrun', 'triggered_by_source_id')
    op.drop_column('annotationrun', 'pipeline_execution_id')
    op.drop_column('annotationrun', 'trigger_context')
    op.drop_column('annotationrun', 'trigger_type')
    op.drop_table('sourcepollhistory')
    # ### end Alembic commands ###
