"""bundle tag fields

Revision ID: 8fecdb0a1bc6
Revises: 343caeaf5873
Create Date: 2025-12-09 00:16:32.285407

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '8fecdb0a1bc6'
down_revision = '343caeaf5873'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotationrun', sa.Column('source_bundle_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_annotationrun_source_bundle_id'), 'annotationrun', ['source_bundle_id'], unique=False)
    op.create_foreign_key(None, 'annotationrun', 'bundle', ['source_bundle_id'], ['id'])
    op.add_column('bundle', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bundle', 'tags')
    op.drop_constraint(None, 'annotationrun', type_='foreignkey')
    op.drop_index(op.f('ix_annotationrun_source_bundle_id'), table_name='annotationrun')
    op.drop_column('annotationrun', 'source_bundle_id')
    # ### end Alembic commands ###
