"""add event_timestamp to datarecord

Revision ID: 94709875c22a
Revises: 35535638c822
Create Date: 2025-04-22 20:02:54.209694

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '94709875c22a'
down_revision = '35535638c822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classificationfield', sa.Column('is_time_axis_hint', sa.Boolean(), nullable=True))
    op.add_column('datarecord', sa.Column('event_timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datarecord', 'event_timestamp')
    op.drop_column('classificationfield', 'is_time_axis_hint')
    # ### end Alembic commands ###
