"""added secure backend key storage

Revision ID: 9b57e934b901
Revises: 4e87dfe21774
Create Date: 2025-11-06 09:14:51.132717

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '9b57e934b901'
down_revision = '4e87dfe21774'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('encrypted_credentials', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'encrypted_credentials')
    # ### end Alembic commands ###
