"""initial migration

Revision ID: a299d7764ded
Revises: 507e47995010
Create Date: 2025-04-26 12:35:48.823567

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a299d7764ded'
down_revision = '507e47995010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasource', sa.Column('data_record_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasource', 'data_record_count')
    # ### end Alembic commands ###
