"""changed status enum to string

Revision ID: a336c5d1020e
Revises: 2d87cf308188
Create Date: 2025-05-07 14:21:52.856652

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a336c5d1020e'
down_revision = '2d87cf308188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
