"""initial migration

Revision ID: a8cd2fdb4169
Revises: a299d7764ded
Create Date: 2025-04-27 11:04:51.575673

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a8cd2fdb4169'
down_revision = 'a299d7764ded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classificationjob', sa.Column('entity_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('classificationjob', sa.Column('imported_from_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_classificationjob_entity_uuid'), 'classificationjob', ['entity_uuid'], unique=True)
    op.create_index(op.f('ix_classificationjob_imported_from_uuid'), 'classificationjob', ['imported_from_uuid'], unique=False)
    op.add_column('classificationscheme', sa.Column('entity_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('classificationscheme', sa.Column('imported_from_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_classificationscheme_entity_uuid'), 'classificationscheme', ['entity_uuid'], unique=True)
    op.create_index(op.f('ix_classificationscheme_imported_from_uuid'), 'classificationscheme', ['imported_from_uuid'], unique=False)
    op.add_column('datarecord', sa.Column('entity_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('datarecord', sa.Column('imported_from_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_datarecord_entity_uuid'), 'datarecord', ['entity_uuid'], unique=True)
    op.create_index(op.f('ix_datarecord_imported_from_uuid'), 'datarecord', ['imported_from_uuid'], unique=False)
    op.add_column('dataset', sa.Column('entity_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('dataset', sa.Column('imported_from_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_dataset_entity_uuid'), 'dataset', ['entity_uuid'], unique=True)
    op.create_index(op.f('ix_dataset_imported_from_uuid'), 'dataset', ['imported_from_uuid'], unique=False)
    op.add_column('datasource', sa.Column('entity_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('datasource', sa.Column('imported_from_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_datasource_entity_uuid'), 'datasource', ['entity_uuid'], unique=True)
    op.create_index(op.f('ix_datasource_imported_from_uuid'), 'datasource', ['imported_from_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasource_imported_from_uuid'), table_name='datasource')
    op.drop_index(op.f('ix_datasource_entity_uuid'), table_name='datasource')
    op.drop_column('datasource', 'imported_from_uuid')
    op.drop_column('datasource', 'entity_uuid')
    op.drop_index(op.f('ix_dataset_imported_from_uuid'), table_name='dataset')
    op.drop_index(op.f('ix_dataset_entity_uuid'), table_name='dataset')
    op.drop_column('dataset', 'imported_from_uuid')
    op.drop_column('dataset', 'entity_uuid')
    op.drop_index(op.f('ix_datarecord_imported_from_uuid'), table_name='datarecord')
    op.drop_index(op.f('ix_datarecord_entity_uuid'), table_name='datarecord')
    op.drop_column('datarecord', 'imported_from_uuid')
    op.drop_column('datarecord', 'entity_uuid')
    op.drop_index(op.f('ix_classificationscheme_imported_from_uuid'), table_name='classificationscheme')
    op.drop_index(op.f('ix_classificationscheme_entity_uuid'), table_name='classificationscheme')
    op.drop_column('classificationscheme', 'imported_from_uuid')
    op.drop_column('classificationscheme', 'entity_uuid')
    op.drop_index(op.f('ix_classificationjob_imported_from_uuid'), table_name='classificationjob')
    op.drop_index(op.f('ix_classificationjob_entity_uuid'), table_name='classificationjob')
    op.drop_column('classificationjob', 'imported_from_uuid')
    op.drop_column('classificationjob', 'entity_uuid')
    # ### end Alembic commands ###
