"""entity canons & graph resolution

Revision ID: af7c577cc17a
Revises: 4dd003f7ac2a
Create Date: 2026-02-06 10:27:22.430556

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'af7c577cc17a'
down_revision = '4dd003f7ac2a'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitycanonical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('infospace_id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['infospace_id'], ['infospace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entity_canonical_infospace_type', 'entitycanonical', ['infospace_id', 'entity_type'], unique=False)
    op.create_index(op.f('ix_entitycanonical_infospace_id'), 'entitycanonical', ['infospace_id'], unique=False)
    op.create_table('fragmentcuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('annotation_id', sa.Integer(), nullable=False),
    sa.Column('fragment_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resolved_refs', sa.JSON(), nullable=True),
    sa.Column('curated_by', sa.Integer(), nullable=True),
    sa.Column('curated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_id'], ['annotation.id'], ),
    sa.ForeignKeyConstraint(['curated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fragment_curation_annotation_path', 'fragmentcuration', ['annotation_id', 'fragment_path'], unique=False)
    op.create_index(op.f('ix_fragmentcuration_annotation_id'), 'fragmentcuration', ['annotation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fragmentcuration_annotation_id'), table_name='fragmentcuration')
    op.drop_index('ix_fragment_curation_annotation_path', table_name='fragmentcuration')
    op.drop_table('fragmentcuration')
    op.drop_index(op.f('ix_entitycanonical_infospace_id'), table_name='entitycanonical')
    op.drop_index('ix_entity_canonical_infospace_type', table_name='entitycanonical')
    op.drop_table('entitycanonical')
    # ### end Alembic commands ###
