"""changed status enum to string

Revision ID: b11a0fba1e33
Revises: c80e8a03691f
Create Date: 2025-05-07 12:05:30.576828

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b11a0fba1e33'
down_revision = 'c80e8a03691f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
