"""decision scratchpad table

Hand-written, not autogenerated. Autogenerate against this database emits ~700
lines of unrelated drift — dropping indexes and foreign keys on `annotation`,
altering `annotationrun` — so only the one new table is declared here.

Revision ID: b1_decision_scratchpad
Revises: a4_source_group
Create Date: 2026-09-23

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "b1_decision_scratchpad"
down_revision = "a4_source_group"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "decision",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        # One dump while the shape is still being found — see modules/logic/models.py.
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("infospace_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["infospace_id"], ["infospace.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_decision_infospace_id"), "decision", ["infospace_id"])
    op.create_index(op.f("ix_decision_user_id"), "decision", ["user_id"])
    op.create_index(op.f("ix_decision_uuid"), "decision", ["uuid"], unique=True)


def downgrade():
    op.drop_index(op.f("ix_decision_uuid"), table_name="decision")
    op.drop_index(op.f("ix_decision_user_id"), table_name="decision")
    op.drop_index(op.f("ix_decision_infospace_id"), table_name="decision")
    op.drop_table("decision")
