"""Stabilising Backup

Revision ID: b44519e6e829
Revises: b1e4b1607246
Create Date: 2025-09-28 13:46:15.328412

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = 'b44519e6e829'
down_revision = 'b1e4b1607246'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbackup', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userbackup', 'expires_at')
    # ### end Alembic commands ###
