"""changed status enum to string

Revision ID: c80e8a03691f
Revises: 696f225b53f7
Create Date: 2025-05-07 12:05:13.535467

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c80e8a03691f'
down_revision = '696f225b53f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
