"""initial migration, 12.05.2025

Revision ID: feb0041beacb
Revises: 83218a79686d
Create Date: 2025-05-21 07:51:51.302043

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'feb0041beacb'
down_revision = '83218a79686d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
