from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool
from alembic.operations import ops
from sqlmodel import SQLModel
import pgvector.sqlalchemy


# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# disable_existing_loggers=False matters now that app/prestart.py runs the DB
# wait, the migration and the seed in one process: the default (True) would
# silence every logger configured before this point — i.e. all of app.* — so
# the seed's output vanished after a migration ran.
if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

# Import all models from the single models.py file
from app.models import *  # This imports all models

# --- ADD THIS SECTION ---
from sqlalchemy_celery_beat.models import ModelBase as CeleryBeatModelBase # Import the base

# Combine your app's metadata with the Celery Beat metadata
target_metadata = [SQLModel.metadata, CeleryBeatModelBase.metadata]



# other values from the config, defined by the needs of env.py,
# can be acquired:
# my_important_option = config.get_main_option("my_important_option")
# ... etc.


def get_url():
    """The app's own URI — not a second derivation of it.

    This used to rebuild the DSN from POSTGRES_* environment variables while the
    application built its own from my-hq.yml. Two derivations of one fact, so
    they could point at different databases — and did: .env said
    `opp_app_users_dev`, my-hq.yml said `opp_app_users`, so `alembic upgrade
    head` migrated a database the app never reads. Worse, POSTGRES_DB is not in
    setup.sh's rendered region, so once .env stops carrying it this fell back to
    the literal default "app".

    settings.SQLALCHEMY_DATABASE_URI already builds exactly this string, scheme
    and sslmode included. Migrations must target whatever the app will read.
    """
    from app.core.config import settings

    return str(settings.SQLALCHEMY_DATABASE_URI)


def run_migrations_offline():
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = get_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        include_schemas=True,
        process_revision_directives=process_revision_directives
    )

    with context.begin_transaction():
        context.run_migrations()


def process_revision_directives(context, revision, directives):
    """
    Inspect autogenerated directives and prepend CREATE SCHEMA statements
    if tables are being created in non-default schemas.
    """
    # There's usually only one directive for a single --autogenerate command
    for directive in directives:
        # Check if the directive has upgrade_ops and if it's not empty
        # This avoids importing MigrationScript directly
        if hasattr(directive, 'upgrade_ops') and directive.upgrade_ops and directive.upgrade_ops.ops:
            upgrade_ops = directive.upgrade_ops.ops
            schemas = set()
            # Iterate through top-level operations/containers
            for op_container in upgrade_ops: 
                 # Handle ops directly within upgrade_ops or inside containers
                 actual_ops = []
                 if hasattr(op_container, 'ops'): # Check if it's a container like ModifyTableOps
                      actual_ops.extend(op_container.ops)
                 else: # Assume it's a direct operation
                      actual_ops.append(op_container)

                 for op in actual_ops:
                      # Check if it's a CreateTableOp and has a schema defined
                      if isinstance(op, ops.CreateTableOp) and op.schema:
                           schemas.add(op.schema)

            # Prepend CREATE SCHEMA for each detected schema if it doesn't exist
            # Insert in reverse order of discovery to maintain relative order if needed,
            # though CREATE SCHEMA order usually doesn't matter.
            # Inserting at index 0 prepends the operations.
            for schema in sorted(list(schemas), reverse=True):
                 print(f"Detected schema '{schema}' in CreateTableOp, prepending CREATE SCHEMA")
                 # Create the execute operation for schema creation
                 create_schema_op = ops.ExecuteSQLOp(f"CREATE SCHEMA IF NOT EXISTS {schema}")
                 # Insert the operation at the beginning of the main upgrade script list
                 directive.upgrade_ops.ops.insert(0, create_schema_op)
    # Note: We are intentionally NOT adding DROP SCHEMA to downgrade directives
    # for safety, as per the recommendation.


def run_migrations_online():
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    configuration = config.get_section(config.config_ini_section)
    configuration["sqlalchemy.url"] = get_url()
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        # Add the 'vector' type to the dialect's ischema_names
        connection.dialect.ischema_names['vector'] = pgvector.sqlalchemy.Vector

        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_schemas=True,
            process_revision_directives=process_revision_directives
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()