apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmaps.redis.name }}
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode no
    maxmemory 6gb
    maxmemory-policy allkeys-lru
    appendonly yes
    port {{ .Values.env.config.REDIS_PORT }}
