apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.env.config.BACKEND_PORT }}
      protocol: TCP
      name: http
  selector:
    app: backend