apiVersion: v1
kind: Service
metadata:
  name: nominatim
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.nominatim.service.type }}
  ports:
    - port: {{ .Values.nominatim.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: nominatim

