"""changed status enum to string

Revision ID: 2089b0474c7c
Revises: a336c5d1020e
Create Date: 2025-05-07 22:47:53.062971

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2089b0474c7c'
down_revision = 'a336c5d1020e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace', sa.Column('system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace', 'system_prompt')
    # ### end Alembic commands ###
