"""changed status enum to string

Revision ID: 2d87cf308188
Revises: b11a0fba1e33
Create Date: 2025-05-07 13:13:27.232273

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2d87cf308188'
down_revision = 'b11a0fba1e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classificationfield', sa.Column('request_justification', sa.Boolean(), nullable=True))
    op.add_column('classificationfield', sa.Column('request_bounding_boxes', sa.Boolean(), nullable=True))
    op.add_column('classificationfield', sa.Column('use_enum_for_labels', sa.Boolean(), nullable=True))
    op.add_column('classificationscheme', sa.Column('default_thinking_budget', sa.Integer(), nullable=True))
    op.add_column('classificationscheme', sa.Column('request_justifications_globally', sa.Boolean(), nullable=True))
    op.add_column('classificationscheme', sa.Column('enable_image_analysis_globally', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classificationscheme', 'enable_image_analysis_globally')
    op.drop_column('classificationscheme', 'request_justifications_globally')
    op.drop_column('classificationscheme', 'default_thinking_budget')
    op.drop_column('classificationfield', 'use_enum_for_labels')
    op.drop_column('classificationfield', 'request_bounding_boxes')
    op.drop_column('classificationfield', 'request_justification')
    # ### end Alembic commands ###
