"""changed status enum to string

Revision ID: 696f225b53f7
Revises: ddd05123ff7f
Create Date: 2025-05-07 11:30:11.412149

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '696f225b53f7'
down_revision = 'ddd05123ff7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classificationresult', 'status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=50),
               nullable=False)
    op.add_column('datarecord', sa.Column('top_image', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('datarecord', sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datarecord', 'images')
    op.drop_column('datarecord', 'top_image')
    op.alter_column('classificationresult', 'status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=7),
               nullable=True)
    # ### end Alembic commands ###
