"""initial migration

Revision ID: 8415346d9015
Revises: ffa018e96eb9
Create Date: 2025-05-01 12:09:37.950383

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8415346d9015'
down_revision = 'ffa018e96eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
