"""added retrying of failed classifications

Revision ID: d662980a39cf
Revises: e999bfb6ef88
Create Date: 2025-05-05 11:43:56.621161

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd662980a39cf'
down_revision = 'e999bfb6ef88'
branch_labels = None
depends_on = None

# ---> Define the Enum object outside functions <---
# Use lowercase values consistent with your Python Enum definition in models.py
classificationresultstatus_enum = sa.Enum('success', 'failed', name='classificationresultstatus')

def upgrade():
    # ### commands auto generated by Alembic - START ###
    # Note: The auto-generated part only added the columns.

    # ---> ADD: Create the ENUM type in the database BEFORE adding the column <---
    classificationresultstatus_enum.create(op.get_bind(), checkfirst=True)

    # Add the 'status' column, initially allowing NULLs
    op.add_column('classificationresult', sa.Column('status', classificationresultstatus_enum, nullable=True))
    # Add the 'error_message' column
    op.add_column('classificationresult', sa.Column('error_message', sa.Text(), nullable=True))

    # ---> ADD: Set a default value for existing rows (assuming 'success' is appropriate) <---
    # Use lowercase 'success' to match the Python enum and likely DB type definition
    op.execute("UPDATE classificationresult SET status = 'success' WHERE status IS NULL")

    # ---> ADD: Make the 'status' column NOT NULL after setting defaults <---
    op.alter_column('classificationresult', 'status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - START ###
    # Note: The auto-generated part only dropped the columns.

    # Drop the columns first
    op.drop_column('classificationresult', 'error_message')
    op.drop_column('classificationresult', 'status')

    # ---> ADD: Drop the ENUM type from the database AFTER dropping the column <---
    classificationresultstatus_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
