"""initial migration

Revision ID: e999bfb6ef88
Revises: 8415346d9015
Create Date: 2025-05-01 14:29:14.657417

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e999bfb6ef88'
down_revision = '8415346d9015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
